[mgr]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse 	 = false
sort_dir_first = true
sort_translit  = false
linemode       = "size_and_mtime"
show_hidden    = true
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 1200
max_height      = 1000
cache_dir       = ""
image_delay     = 30
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]
# [[plugin.prepend_fetchers]]
# id   = "git"
# name = "*"
# run  = "git"
#
# [[plugin.prepend_fetchers]]
# id   = "git"
# name = "*/"
# run  = "git"
[plugin]
prepend_previewers = [
    { mime = "audio/*",   run = "exifaudio"}
]
[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '$EDIT "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'imv "$@"', desc = "Open" },
]
music = [{run = 'ffplay "$@"',desc = "Open"}]
[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },
    {name = "*.jpg" , use = "open"},
    {name = "*.png" , use = "open"},
	# { mime = "application/json", use = "edit" },
	{ name = "*.json", use = "edit" },
    {name = "*.py" , use = "edit"},
	{ name = "*.cpp", use = "edit" },
    {name = "*.conf" , use = "edit"},
	{ name = "*.lua", use = "edit" },
    {name = "*.toml" , use = "edit"},
	# Multiple openers for a single rule
	{ name = "*.html", use = [ "open", "edit" ] },
	{name = "*.mp3", use = "music"},
]
